language: python
dist: focal

install:
  - pip install pip --upgrade
  - pip install "poetry<1.8"
  - travis_retry poetry install

before_script:
  - export TZ=Asia/Tokyo
  - sudo ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  - echo "Asia/Tokyo" > sudo tee /etc/timezone  > /dev/null

script:
  # webapiにアクセスするテストは実行しないようにする
   - poetry run pytest -n auto -m "not access_webapi"


jobs:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11
      script:
        # 開発環境と同じPythonバージョンのみlintを実行する
        - make lint
    - python: 3.12


branches:
  only:
      - main

cache: pip
