language: python
dist: focal

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

install:
  - pip install pip --upgrade
  - pip install "poetry<1.8"
  - travis_retry poetry install

before_script:
  - export TZ=Asia/Tokyo
  - sudo ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  - echo "Asia/Tokyo" > sudo tee /etc/timezone  > /dev/null

script:
   - make lint
  # webapiにアクセスするテストは実行しないようにする
   - poetry run pytest -n auto -m "not access_webapi"

branches:
  only:
      - main

env:
  # `poetry install`時に`Max retries exceeded with`が発生しないようにするため、タイムアウト時間を指定する
  - PIP_DEFAULT_TIMEOUT=300

cache: pip
